import type { Metadata } from "next";
import "./globals.css";
import { UberMove, SFPro } from "@/lib/fonts";
import Cursor from "@/components/pages/global/cursor";
import { Footer } from "@/components/pages";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${UberMove.className} ${SFPro.className} antialiased`}>
        {/* <Cursor /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
